name: Generate Content

on:
  schedule:
    - cron: '0 * * * *'  # Запуск каждый час
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Установка Python и зависимостей
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install transformers torch

      - name: Запуск скрипта генерации контента
        run: python3 generate_content.py

      - name: Commit и push изменений
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Настраиваем данные пользователя Git (будет использован GitHub Actor)
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          
          # Добавляем все изменения
          git add .
          
          # Если изменений нет, выводим сообщение, но не завершаем работу с ошибкой
          git commit -m "Автоматическая генерация контента" || echo "No changes to commit"
          
          # Пушим изменения, используя GITHUB_TOKEN для аутентификации
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
